# Generated by Django 5.0.6 on 2024-11-23 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0001_initial'),
    ]

    operations = [
    ]
