# Generated by Django 5.0.6 on 2024-11-23 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0003_alter_arbol_edad_aproximada_alter_arbol_especie_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Arbol',
        ),
    ]
