# Generated by Django 5.0.6 on 2024-11-23 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0004_delete_arbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=100)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('edad_aproximada', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='arboles/')),
            ],
        ),
    ]
