# Generated by Django 5.0.6 on 2024-11-24 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0005_arbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbol',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/arboles_imagenes'),
        ),
    ]
