# Generated by Django 5.0.6 on 2024-11-24 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0006_alter_arbol_imagen'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='arbol',
            table='mi_aplicacion_arbol',
        ),
    ]
