# Generated by Django 5.0.6 on 2024-11-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0007_alter_arbol_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbol',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='arboles_imagenes/'),
        ),
        migrations.AlterField(
            model_name='arbol',
            name='latitud',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='arbol',
            name='longitud',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterModelTable(
            name='arbol',
            table=None,
        ),
    ]
