# Generated by Django 5.0.6 on 2024-11-24 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0008_alter_arbol_imagen_alter_arbol_latitud_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Arbol',
        ),
    ]
