# Generated by Django 5.1.3 on 2024-11-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0010_arbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbol',
            name='cuidados',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arbol',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arbol',
            name='riego_por_semana',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
